<a href="https://colab.research.google.com/github/The1AndOnlyAlex/PyTorch-MNIST/blob/main/crossentropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch
#plt.style.use(['science', 'notebook'])

In [3]:
p = np.array([5,1,4,6,2,4])
q1 = p
q2 = np.array([3,7,1,4,1,6])
q3 = np.array([2,5,7,2,1,5])

In [4]:
-sum(p*np.log(q1))

np.float64(-31.27439562761785)

# **For Multiple Images**

In [5]:
p = np.zeros((4,10), dtype=int)
p[0][4] = 1
p[1][2] = 1
p[2][8] = 1
p[3][6] = 1

In [6]:
p

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [7]:
# Create probability array of qs:
q = np.random.rand(40).reshape(4,10)
q = q/np.expand_dims(np.sum(q, axis=1), axis=1)
q

array([[0.02867138, 0.16417361, 0.13568417, 0.17043897, 0.05561976,
        0.07776933, 0.14792044, 0.15457884, 0.05967904, 0.00546445],
       [0.14565902, 0.11292818, 0.06952526, 0.08502471, 0.04936745,
        0.15136419, 0.17221032, 0.00860954, 0.04627086, 0.15904047],
       [0.09424771, 0.06137336, 0.00484132, 0.18496192, 0.19110248,
        0.13560085, 0.00061137, 0.16563315, 0.03325838, 0.12836946],
       [0.08455787, 0.08115722, 0.14718134, 0.0698019 , 0.12452692,
        0.09795568, 0.09294808, 0.13905002, 0.01912573, 0.14369524]])

In [8]:
# Compute H for each term in the sum and then sum together
# to get L
q[p>0]

array([0.05561976, 0.06952526, 0.03325838, 0.09294808])

In [9]:
Hs = -np.log(q[p>0])
L = sum(Hs)

In [10]:
Hs

array([2.88921673, 2.66606517, 3.40344837, 2.37571422])

In [11]:
L

np.float64(11.33444449779325)

# **How do we get the $q$'s in Machine Learning?**

q should be related to a probability density function

- Bounded between 0 and 1
- The closer to 0, the less likely we are confident that image n is class c
- The closer to 1, the more likely we are confident that image n is class c
- Sum all $q_c$ = 1 for each image (we enforced this above in a different way)

In [12]:
yhat = 20*np.random.rand(40).reshape(4,10) **2

In [13]:
yhat

array([[1.27995833e+00, 4.48474641e-01, 2.97950308e+00, 8.82006155e+00,
        4.79559935e+00, 9.62594560e+00, 1.85056067e+01, 8.99800828e-02,
        8.66236000e+00, 5.22517461e+00],
       [1.40614500e+00, 7.30810478e-01, 8.43817967e+00, 2.13152672e+00,
        1.74224107e+00, 7.72255970e+00, 3.52748461e+00, 1.59133470e+01,
        9.47059046e+00, 4.21030332e+00],
       [5.35284400e+00, 1.15932211e+00, 1.74767366e+01, 8.90498294e+00,
        1.04647018e+01, 1.12248930e-03, 8.39718648e-01, 5.45360789e-01,
        1.51727481e+01, 2.01572434e+00],
       [7.91506525e+00, 8.31372077e+00, 7.55182550e+00, 1.33195612e+01,
        1.47908092e+01, 1.92498301e+01, 1.18611454e+01, 1.30420675e+01,
        7.19666378e+00, 5.85756445e+00]])

In [14]:
q = np.exp(yhat)
q

array([[3.59648985e+00, 1.56592177e+00, 1.96780357e+01, 6.76868126e+03,
        1.20976868e+02, 1.51528756e+04, 1.08863642e+08, 1.09415249e+00,
        5.78116212e+03, 1.85893627e+02],
       [4.08019591e+00, 2.07676310e+00, 4.62013717e+03, 8.42772381e+00,
        5.71012590e+00, 2.25873388e+03, 3.40382405e+01, 8.14852093e+06,
        1.29725447e+04, 6.73769734e+01],
       [2.11208121e+02, 3.18777159e+00, 3.89090184e+07, 7.36859951e+03,
        3.50559906e+04, 1.00112312e+00, 2.31571535e+00, 1.72523071e+00,
        3.88544497e+06, 7.50616242e+00],
       [2.73822519e+03, 4.07946351e+03, 1.90421570e+03, 6.08992468e+05,
        2.65195910e+06, 2.29136873e+08, 1.41654376e+05, 4.61421613e+05,
        1.33496957e+03, 3.49870977e+02]])

In [20]:
np.sum(q, axis=1).shape

(4,)

In [21]:
# Currently (4,) but must expand to (4,1)
np.expand_dims(np.sum(q, axis=1), axis=1).shape

(4, 1)

In [25]:
q = q/np.expand_dims(np.sum(q, axis=1), axis=1)
q

array([[3.30281426e-08, 1.43805459e-08, 1.80712026e-07, 6.21597665e-05,
        1.11098360e-06, 1.39155498e-04, 9.99742537e-01, 1.00480819e-08,
        5.30909455e-05, 1.70714265e-06],
       [4.99504055e-07, 2.54240633e-07, 5.65604521e-04, 1.03173532e-06,
        6.99042671e-07, 2.76517784e-04, 4.16701539e-06, 9.97554858e-01,
        1.58811950e-03, 8.24839596e-06],
       [4.93049359e-06, 7.44161132e-08, 9.08301562e-01, 1.72014374e-04,
        8.18355548e-04, 2.33704609e-08, 5.40586209e-08, 4.02742042e-08,
        9.07027698e-02, 1.75225676e-07],
       [1.17514692e-05, 1.75075774e-05, 8.17220296e-06, 2.61357474e-03,
        1.13812464e-02, 9.83372334e-01, 6.07929192e-04, 1.98025417e-03,
        5.72920511e-06, 1.50151931e-06]])

In [27]:
q.sum(axis=1)

array([1., 1., 1., 1.])

In [28]:
p

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [30]:
c_squig = np.where(p)
c_squig

(array([0, 1, 2, 3]), array([4, 2, 8, 6]))

Compute the loss function:

In [32]:
q[c_squig]

array([1.11098360e-06, 5.65604521e-04, 9.07027698e-02, 6.07929192e-04])

In [33]:
Hs = -np.log(q[c_squig])
L = sum(Hs)
L

np.float64(30.993499784690908)

# **PyTorch Equivalent**

Create loss function

In [35]:
L = torch.nn.CrossEntropyLoss(reduction='sum')

Evaluate on data above:

In [36]:
L(torch.tensor(yhat), torch.tensor(p, dtype=torch.float))

tensor(30.9935, dtype=torch.float64)